export const data = {
  specialities: [
    "Advertising layout",
    "Logo & Branding",
    "Packaging Design",
    "UX/UI Design",
    "Web Design",
    "Vector Illustration",
    "Pattern Making",
  ],
  knowledge: [
    "Grid & Layout",
    "Good sense for typography",
    "Good drawing skill",
    "Color theory",
    "Image editing",
    "Web usability",
    "Research analysis",
  ],
  softwares: [
    ["Figma/Sketch", 100],
    ["Principle", 80],
    ["Adobe Illustrator", 100],
    ["Adobe Acrobat", 100],
    ["Adobe Photoshop", 75],
    ["Adobe XD", 75],
    ["Adobe Indesign", 75],
    ["Adobe After Effects", 60],
    ["Adobe Lightroom", 60],
    ["Affinity Designer", 100],
    ["Affinity Photo", 80],
    ["Affinity Publisher", 80],
    ["Cinema 4D", 75],
    ["HTML & CSS", 60],
  ],
}
