export const data = {
    specialities: [
        "advertising layout",
        "Logo & Branding",
        "Packaging Design",
        "UX/UI Design",
        "Web Design",
        "Vector Illustration",
        "Pattern Making",
    ],
    knowledge: [
        "Grid & Layout",
        "Good sense for typography",
        "Good drawing skill",
        "Color theory",
        "Image editing",
        "Web usability",
        "Research analysis",
    ],
    softwares: [
        ["Adobe Photoshop", 75],
        ["Adobe Illustrator", 75],
        ["Adobe Indesign", 75],
        ["Adobe XD", 75],
        ["Adobe After Effects", 75],
        ["Adobe Lightroom", 75],
        ["Adobe Acrobat", 75],
        ["Affinity Photo", 75],
        ["Affinity Designer", 75],
        ["Affinity Publisher", 75],
        ["Figma/Sketch", 75],
        ["Principle", 75],
        ["Cinema 4D", 75],
        ["HTML & CSS", 75],
    ],
}